"""additions

Revision ID: a6445cfc34a5
Revises: f460cc007e23
Create Date: 2018-04-25 17:07:44.512694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6445cfc34a5'
down_revision = 'f460cc007e23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('followers', sa.Column('followed_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'followers', 'user', ['followed_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'followers', type_='foreignkey')
    op.drop_column('followers', 'followed_id')
    # ### end Alembic commands ###
